---
# Notes:
#   - Let playbooks govern the order and scope of the tasks
#     as required.
#   - Put as much code as possible into Roles since they have
#     support for re-use (e.g. via ansible-galaxy).
- hosts: all
  tasks:
    - name: Set dev/test related facts
      set_fact:
        debug_info: no
        test_update_local_dns: yes

- hosts: all
  become: yes
  tasks:
      - name: Test that this can create create a file
        command: /usr/bin/touch /tmp/test_from_site.yml
        when: debug_info

- name: Dump All Ansible Variables
  hosts: all
  tasks:
    - name: Dump all variables
      include_role:
        name: dump-all-variables
      when: debug_info

- name: Update local DNS
  hosts: all
  vars:
    local_dns_group: "all"
  tasks:
    - name: Update local DNS on all hosts with Ansible Group {{ local_dns_group }}
      include_role:
        name: update-local-dns
      when: test_update_local_dns

