---

- name: Set dev-related Facts
  hosts: all
  tasks:
    - name: Set some facts
      set_fact:
        dump_all_variables: yes
        update_local_dns: yes
        install_kubespray: yes

- name: Dump All Variables
  import_playbook: dump-all-variables.yml
  when: dump_all_variables

- name: Update Local DNS
  import_playbook: update-local-dns.yml
  when: update_local_dns
        
- name: Install Kubespray
  import_playbook: install-kubespray.yml
  when: install_kubespray
