---
- hosts: all
  tasks:
    - name: Set dev/test related facts
      set_fact:
        debug_info: yes

- hosts: all
  become: yes
  tasks:
      - name: Test that this can create create a file
        command: /usr/bin/touch /tmp/test_from_site.yml
        when: debug_info is defined and debug_info == True

- name: Dump All Ansible Variables
  hosts: all
  become: yes
  tasks:
    - name: Dump all variables
      include_role:
        name: dump-all-variables
      when: debug_info is defined and debug_info == True
