---
# Notes:
#   - Let playbooks govern the order and scope of the tasks
#     as required.
#   - Put as much code as possible into Roles since they have
#     support for re-use (e.g. via ansible-galaxy).

- name: Set dev-related Facts
  hosts: all
  tasks:
    - name: Set some facts
      set_fact:
        debug_info: yes
        update_local_dns: yes
        configure_kubespray_user: yes
        install_kubespray: yes        

- name: Dump All Ansible Variables
  hosts: all
  become: yes
  tasks:
    - name: Dump all variables
      include_role:
        name: dump-all-variables
      when: debug_info

- name: Update local DNS
  hosts: all
  vars:
    local_dns_group: "all"
  tasks:
    - name: Update local DNS on all hosts with Ansible Group {{ local_dns_group }}
      include_role:
        name: update-local-dns
      when: update_local_dns

- name: Configure Kubespray User
  import_playbook: configure-kubespray-user.yml
  when: configure_kubespray_user

- name: Install Kubespray
  hosts: kube-master[0]
  become: yes
  become_user: "{{ kubespray_user }}"  
  tasks:
    - name: TEST
      debug:
        msg="TEST"
      when: install_kubespray
    - name: Install Kubespray
      include_role:
        name: install-kubespray
      when: install_kubespray

        