---
- hosts: all
  become: yes

tasks:
- name: create a complete empty file
  command: /usr/bin/touch /test/test.conf


#- name: Add IP address of all hosts to all hosts
#  lineinfile:
#      dest: /etc/hosts
#      regexp: '.*{{ item }}$'
#      line: "{{ hostvars[item].ansible_host }} {{item}}"
#      state: present
#      when: hostvars[item].ansible_host is defined
#      with_items: "{{ groups.all }}"
#
#- debug: msg="USER={{lookup('env','USER')}}"
#- debug: msg="GROUPS={{groups}}"
#