---
- name: Dump All Variables
  import_playbook: dump-all-variables.yml
  tags: [ never, debug ]

- name: Update Local DNS
  import_playbook: update-local-dns.yml
  # tags: [ never, debug ]  
        
- name: Install Kubespray
  import_playbook: install-kubespray.yml

