- name: Print some debug information
  vars:
    ansible_vars_msg_json: |
        {
        "SOURCE_vars": {{ vars | to_nice_json }},
        "SOURCE_environment": {{ environment | to_nice_json }},
        "SOURCE_group_names": {{ group_names | to_nice_json }},
        "SOURCE_groups": {{ groups | to_nice_json }},
        "SOURCE_hostvars": {{ hostvars | to_nice_json }},
        }
  block:
    - name: Show debug data
      debug:
        msg: "{{ ansible_vars_msg_json }}"
      tags: debug_info
    - name: Write debug information to a file
      copy:
        content: "{{ ansible_vars_msg_json }}"
        dest: "/root/ansible_vars.json"
  become: yes
