# Vagrant installs a newer ansible in /home/vagrant/.local/bin/ansible
# and puts it in PATH.
# But, we might provision without Vagrant, so don't rely on it.
#/usr/bin/ansible --version

- name: Run Command
  command: "ansible --version"
  register: results  

- name: Show Command Results
  debug:
    msg: "{{ results }}"

- name: Run Shell
  shell: "ansible --version"
  register: results

- name: Show Shell Results
  debug:
    msg: "{{ results }}"

- name: Install Ansible via APT
  become: yes
  apt:
    name: ansible
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  #tags: [ never ]

