- name: Install SSH config file
  template:
    src: templates/ssh/config.j2
    dest: "{{ kubespray_user_dir }}/.ssh/config"
    mode: '0644'

- name: Install Kubespray Git Repo
  git:
    repo: "{{ kubespray_repo }}"
    dest: "{{ kubespray_user_dir }}/kubespray"
    version: "{{ kubespray_version }}"
    force: yes
    
- name: Install Kubespray Python requirements
  become: yes
  pip:
    requirements: "{{ kubespray_user_dir }}/kubespray/requirements.txt"
    executable: "pip3"
  #tags: [ never, debug ]

- name: Copy Sample Config files
  command: "cp -rfp {{ src }} {{ dest }}"
  vars:
    src: "{{ kubespray_user_dir }}/kubespray/inventory/sample"
    dest: "{{ kubespray_user_dir }}/kubespray/inventory/mycluster"
    
- name: Install Kubespray inventory file
  template:
    src: templates/inventory/hosts.ini.j2
    dest: "{{ kubespray_user_dir }}/kubespray/inventory/mycluster/hosts.yml"
    mode: '0700'

- name: Run Kubespray
  command: "{{ ansible_playbook }} -i {{ hosts_yml }} --become --become-user=root {{ playbook }}"
  args:
    chdir: "{{ kubespray_user_dir }}/kubespray"
  vars:
    ansible_playbook: "/usr/local/bin/ansible-playbook"
    hosts_yml: "{{ kubespray_user_dir }}/kubespray/inventory/mycluster/hosts.yml"
    playbook: "cluster.yml"
  register: result

- name: Show Kubespray results
  debug:
    msg: "{{ result }}"