# Use the ansible user, but support changing it here.
- name: Assign kubespray user facts
  set_fact:
    kubespray_user_id: "{{ ansible_user_id }}"
    kubespray_user_dir: "{{ ansible_user_dir }}"    

- name: Install Kubespray Git Repo
  git:
    repo: "{{ kubespray_repo }}"
    dest: "{{ kubespray_user_dir }}/kubespray"
    version: "{{ kubespray_version }}"
    force: yes
    #tags: [ never, debug ]
    
- name: Install Kubespray Python requirements
  become: yes
  pip:
    requirements: "{{ kubespray_user_dir }}/kubespray/requirements.txt"
    executable: "pip3"
    #tags: [ never, debug ]
