- name: Install SSH config file
  template:
    src: templates/ssh/config.j2
    dest: "{{ kubespray_user_dir }}/.ssh/config"
    mode: '0644'
  #tags: [ never, debug ]

- name: Install Kubespray Git Repo
  git:
    repo: "{{ kubespray_repo }}"
    dest: "{{ kubespray_user_dir }}/kubespray"
    version: "{{ kubespray_version }}"
    force: yes
  #tags: [ never, debug ]
    
- name: Install Kubespray Python requirements
  become: yes
  pip:
    requirements: "{{ kubespray_user_dir }}/kubespray/requirements.txt"
    executable: "pip3"
  #tags: [ never, debug ]

- name: Create directories for my cluster
  copy:
    src: "{{ kubespray_user_dir }}/kubespray/inventory/sample"
    dest: "{{ kubespray_user_dir }}/kubespray/inventory/mycluster"
    mode: preserve    
    
- name: Install Kubespray inventory file
  template:
    src: templates/inventory/hosts.ini.j2
    dest: "{{ kubespray_user_dir }}/kubespray/inventory/mycluster/hosts.ini"
    mode: '0700'