---
galaxy_info:
  author: "Phillip W. Young"
  company: State Street
  min_ansible_version: 2.1
  platforms:
    - name: CentOS
      versions:
        - 7
#    - name: Ubuntu
#      versions:
#        - xenial
#        - artful
#        - bionic
dependencies: []
